version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:latest
    container_name: flyway_migrations
    depends_on:
      - postgres
    command: -url=jdbc:postgresql://postgres:5432/mydatabase -user=myuser -password=mypassword migrate
    volumes:
      - ./flyway/sql:/flyway/sql

volumes:
  pgdata: